# Import Libraries

In [3]:
# Import NumPy
import numpy as np

# Numpy Array Slicing & Indexing

In [4]:
# 1D Array Slicing and Indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
arr[1:4]

array([2, 3, 4])

In [5]:
arr[1:8:2]


array([2, 4, 6, 8])

In [6]:
arr[-3]

np.int64(8)

In [7]:
# 2D Array Indexing
_2d_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
_2d_array[1:2]

array([[4, 5, 6]])

In [8]:

_2d_array[1, 2]

np.int64(6)

In [9]:

_2d_array[1]

array([4, 5, 6])

In [10]:

_2d_array[:, 0]

array([1, 4, 7])

# Sorting

In [11]:
# Sorting Arrays
unsorted = np.array([1, 5, 7, 3, 9, 4, 1, 7, 2, 4, 5])
np.sort(unsorted)

array([1, 1, 2, 3, 4, 4, 5, 5, 7, 7, 9])

In [12]:
arr_2d_unsorted = np.array([
    [3, 1],
    [1, 4],
    [2, 3]
])
np.sort(arr_2d_unsorted, axis=0)

array([[1, 1],
       [2, 3],
       [3, 4]])

# Filtering

In [13]:
# Filtering Arrays
_numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
_numbers[_numbers % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [14]:
# Filter with mask
mask = _numbers > 5
_numbers[mask]

array([ 6,  7,  8,  9, 10])

# np.where()

In [15]:
# Fancy Indexing vs np.where()
indices = [1, 2, 4]
_numbers[indices]

array([2, 3, 5])

In [18]:
where_result = np.where(_numbers > 5)
where_result

(array([5, 6, 7, 8, 9]),)

In [20]:
_numbers[where_result]

array([ 6,  7,  8,  9, 10])

In [21]:
# Conditional Assignment using np.where
condition_arr = np.where(_numbers > 5, _numbers * 2, _numbers)
condition_arr

array([ 1,  2,  3,  4,  5, 12, 14, 16, 18, 20])

# Adding and Concatenating Arrays

In [22]:
# Adding and Concatenating Arrays

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
combined_arr = arr_1 + arr_2
combined_arr

array([5, 7, 9])

In [24]:

concatenated_arr = np.concatenate((arr_1, arr_2))
concatenated_arr

array([1, 2, 3, 4, 5, 6])

# Rows & Columns

In [25]:
# Array Compatibility
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])
a.shape == b.shape


False

In [27]:
# Adding new row
original = np.array([[1, 2], [7, 8]])
original

array([[1, 2],
       [7, 8]])

In [28]:

new_row = np.array([[5, 6]])
with_new_row = np.vstack((original, new_row))
with_new_row

array([[1, 2],
       [7, 8],
       [5, 6]])

In [29]:
# Adding new column
new_col = np.array([[16], [17]])
with_new_col = np.hstack((original, new_col))
with_new_col

array([[ 1,  2, 16],
       [ 7,  8, 17]])

# Deleting Elements

In [30]:
# Deleting Elements
new_arr = np.array([1, 2, 3, 4, 5])
new_arr

array([1, 2, 3, 4, 5])

In [31]:

deleted = np.delete(new_arr, 2)
deleted

array([1, 2, 4, 5])