# Import Libraries

In [1]:
import numpy as np

# Creating Arrays

In [7]:
# Creating a 1D NumPy array
np.array([1, 5, 6])

array([1, 5, 6])

In [8]:
# Creating a 2D NumPy array (matrix)
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

# Multiplication

In [9]:
# Python list multiplication (concatenation)
py_list = [1, 2, 3]
py_list * 2

[1, 2, 3, 1, 2, 3]

In [10]:
# NumPy array multiplication (element-wise)
np_arr = np.array([1, 2, 3])
np_arr * 2

array([2, 4, 6])

# Python List vs Numpy Array

In [11]:
import time

# Time taken for list comprehension
start = time.time()
py_list = [i * 2 for i in range(100000)]
time.time() - start

0.0718994140625

In [12]:
# Time taken using NumPy vectorized operation
start = time.time()
np_array = np.arange(100000 * 2)
time.time() - start

0.0014071464538574219

# Creating Numpy Arrays

In [13]:
# Creating a 3x4 array filled with zeros
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# Creating a 6x9 array filled with ones
ones = np.ones((6, 9))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
# Creating a 4x5 array filled with the value 5
full = np.full((4, 5), 5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
# Creating a 4x6 array with random values
random = np.random.random((4, 6))
random

array([[0.5494455 , 0.72820932, 0.03453269, 0.88426846, 0.49520823,
        0.23211212],
       [0.58134704, 0.44691835, 0.35897722, 0.22314536, 0.27530076,
        0.89763558],
       [0.86569255, 0.46299066, 0.04351115, 0.24360868, 0.92664935,
        0.42894663],
       [0.77932409, 0.53891093, 0.59502701, 0.01976876, 0.03188397,
        0.38608508]])

In [17]:
# Creating a sequence from 1 to 101 with step 4
sequence = np.arange(1, 102, 4)
sequence

array([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
        53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101])

# Vector, Matrix & Tensor

In [18]:
# Creating a vector (1D array)
vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

In [19]:
# Creating a matrix (2D array)
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# Creating a tensor (3D array - list of matrices)
tensor = [
    [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
    [[21, 22, 23], [24, 25, 26], [27, 28, 29]],
    [[31, 32, 33], [34, 35, 36], [37, 38, 39]]
]
tensor

[[[11, 12, 13], [14, 15, 16], [17, 18, 19]],
 [[21, 22, 23], [24, 25, 26], [27, 28, 29]],
 [[31, 32, 33], [34, 35, 36], [37, 38, 39]]]

# Numpy Array Properties

In [22]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr.shape

(2, 3)

In [24]:
arr.ndim

2

In [25]:
arr.size

6

In [26]:
arr.dtype

dtype('int64')

# Numpy Array Properties & Methods

In [27]:
# Creating a 1D array of 12 elements
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:

# Reshaping to 4x3
reshaped = arr.reshape((4, 3))
reshaped

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:


# Flattening the reshaped array (returns a copy)
flattened = reshaped.flatten()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:


# Raveling the array (returns a view if possible)
raveled = reshaped.ravel()
raveled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:


# Transposing the reshaped array
transposed = reshaped.T
transposed

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])